[build]
  publish = "."

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/patient"
  to = "/patient.html"
  status = 200

[[redirects]]
  from = "/book"
  to = "/book.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
